### ISSUE TITLE
Half precision 6B model?

### ISSUE THREAD

**Issue by lambdaofgod** [dpfried/incoder#1]
I'm having troubles with loading 6B model even on RTX3090 - is there a possibility you would share the model weights in half precision format?

Anyway, thank you for your work, the model looks great.

**Comment by dpfried** [comment]
I've uploaded the weights in half precision to the HF Hub repo, with instructions on how to load them in the model card: https://huggingface.co/facebook/incoder-6B.

I've also updated the example_usage.py script here to use these half-precision weights by default.

Please let me know if you still run into issues, and thanks for your interest!
