### ISSUE TITLE
Generating SQL statements (Discussion-Topic)

### ISSUE THREAD

**Issue by OleApp** [dpfried/incoder#11]
Hi all!

I am trying to generate SQL statements with the InCoder model.
The first attempts look very promising!
Does anyone have an idea how I can prompt the model with my database structure?
Something trivial like what tables and attributes are there.

Thanks for any food for thought!
Greetings, Ole

**Comment by dpfried** [comment]
Hi Ole, Thanks for your interest! Perhaps others could weigh in here as well, but I would recommend looking the setup that Freda and some of us used in this paper: https://arxiv.org/abs/2204.11454, https://github.com/facebookresearch/mbr-exec for the Spider experiments. I am not sure whether this <info> formatting would work well with InCoder, but it might.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/945436/198831943-72894a24-d773-40b1-a686-4e94b7cab99c.png">

**Comment by OleApp** [comment]
Hi @dpfried!
Thank you very much for your response and the hint!
It works like a charm! It was possible for me to generate even nested queries!

Best regards, Ole!
