### ISSUE TITLE
Demo unavailable

### ISSUE THREAD

**Issue by michaelmior** [dpfried/incoder#17]
The demo on HuggingFace spaces currently produces a runtime error

**Comment by dpfried** [comment]
Unfortunately I'm no longer a member of the `facebook` organization on HF spaces after leaving Meta, so I'm unable to debug this, and the model is too large to run on a free spaces instance when I try to clone it. I'd recommend cloning the repository https://huggingface.co/spaces/facebook/incoder-demo and running it locally, if you are interested to try the demo.

**Comment by michaelmior** [comment]
Thanks for the reply. It might be good to update the readme to remove the demo link.

**Comment by dpfried** [comment]
Thanks for the suggestion! I've added a note that the demo's not working, but left the link in as the code might potentially be useful.
